/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iu;

import java.awt.Frame;

/**
 *
 * @author facun
 */
//public class BaseVistaImpl extends javax.swing.JDialog {
public abstract class BaseVistaImpl extends javax.swing.JDialog implements BaseVista{
    /**
     * Creates new form BaseVista
     */
    public BaseVistaImpl() {
//        super(parent, modal);
        initComponents(); // asegurate que este método exista o esté implementado en subclases
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblMensajeError.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensajeError, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        avisarAlControladorDelPedidoDeCierre();
    }//GEN-LAST:event_formWindowClosing
    @Override
    public void mostrarMensajeDeError(String mensaje) {
        lblMensajeError.setText(mensaje);
    }
    @Override
    public void limpiarMensajeDeError() {
        lblMensajeError.setText("");
    }
    
    @Override
    public void cerrar(){
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMensajeError;
    // End of variables declaration//GEN-END:variables
    
    //Metodo para evitar tener el controlador en este nivel de la vista. Cada subclase lo sobreescribe para visar al
    protected abstract void avisarAlControladorDelPedidoDeCierre();
}
